In [45]:
import pandas as pd
import numpy as np
import locale

In [8]:
pd.set_option('display.max_columns', None)

In [10]:
df = pd.read_csv('HouseData.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25155 entries, 0 to 25154
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                25155 non-null  int64
 1   district                  25155 non-null  object
 2   price                     25155 non-null  object
 3   address                   25155 non-null  object
 4   AdUpdateDate              25155 non-null  object
 5   Category                  25155 non-null  object
 6   GrossSquareMeters         25155 non-null  object
 7   BuildingAge               25155 non-null  object
 8   NumberFloorsofBuilding    25155 non-null  int64
 9   UsingStatus               25155 non-null  object
 10  EligibilityForInvestment  21506 non-null  object
 11  BuildStatus               11231 non-null  object
 12  TitleStatus               9712 non-null   object
 13  ItemStatus                18332 non-null  object
 14  NumberOfBathrooms         25155 non-null  object
 15  NumberOfWCs               8129 non-null   object
 16  AdCreationDate            25155 non-null  object
 17  Type                      25155 non-null  object
 18  NetSquareMeters           25155 non-null  object
 19  NumberOfRooms             25155 non-null  object
 20  FloorLocation             25155 non-null  object
 21  HeatingType               25155 non-null  object
 22  CreditEligibility         25155 non-null  object
 23  InsideTheSite             25155 non-null  object
 24  StructureType             10406 non-null  object
 25  MortgageStatus            6058 non-null   object
 26  Swap                      20839 non-null  object
 27  Balcony                   9109 non-null   object
 28  PriceStatus               25155 non-null  object
 29  RentalIncome              5815 non-null   object
 30  NumberOfBalconies         5324 non-null   object
 31  BalconyType               4720 non-null   object
 32  HallSquareMeters          1433 non-null   object
 33  WCSquareMeters            865 non-null    object
 34  IsItVideoNavigable?       5481 non-null   object
 35  Subscription              4488 non-null   object
 36  BathroomSquareMeters      1112 non-null   object
 37  BalconySquareMeters       1040 non-null   object
dtypes: int64(2), object(36)
memory usage: 7.3+ MB

In [14]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [16]:
df.head()

,district,price,address,AdUpdateDate,Category,GrossSquareMeters,BuildingAge,NumberFloorsofBuilding,UsingStatus,EligibilityForInvestment,BuildStatus,TitleStatus,ItemStatus,NumberOfBathrooms,NumberOfWCs,AdCreationDate,Type,NetSquareMeters,NumberOfRooms,FloorLocation,HeatingType,CreditEligibility,InsideTheSite,StructureType,MortgageStatus,Swap,Balcony,PriceStatus,RentalIncome,NumberOfBalconies,BalconyType,HallSquareMeters,WCSquareMeters,IsItVideoNavigable?,Subscription,BathroomSquareMeters,BalconySquareMeters
0,adalar,"3,100,000TL","['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",24 Şubat 2022,Satılık,160 m2,21 Ve Üzeri,3,Mülk Sahibi Oturuyor,Bilinmiyor,NaN,NaN,Eşyalı,2,NaN,24 Şubat 2022,Konut,120 m2,3+1,Çatı Katı,Kombi Doğalgaz,Krediye Uygun,Hayır,NaN,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,adalar,"1,600,000TL","['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",02 Mart 2022,Satılık,120 m2,5-10,3,Mülk Sahibi Oturuyor,Yatırıma Uygun,İkinci El,Kat Mülkiyeti,Eşyalı,1,1,21 Şubat 2022,Konut,100 m2,2+1,Bahçe Katı,Kombi Doğalgaz,Krediye Uygun,Hayır,Betonarme,Yok,Yok,Var,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,adalar,"18,500,000TL","['Anasayfa', 'Satılık Müstakil Ev', 'İstanbul ...",11 Şubat 2022,Satılık,350 m2,21 Ve Üzeri,2,Mülk Sahibi Oturuyor,Bilinmiyor,NaN,NaN,Boş,3,NaN,11 Şubat 2022,Konut,300 m2,3+1,Düz Giriş,Kombi Doğalgaz,Krediye Uygun,Hayır,NaN,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,adalar,"9,500,000TL","['Anasayfa', 'Satılık Bina', 'İstanbul Satılık...",11 Şubat 2022,Satılık,550 m2,11-15,3,Mülk Sahibi Oturuyor,Bilinmiyor,İkinci El,NaN,NaN,4,NaN,03 Şubat 2022,Konut,540 m2,8+ Oda,Düz Giriş,Kombi Doğalgaz,Krediye Uygun Değil,Hayır,Betonarme,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,adalar,"25,000,000TL","['Anasayfa', 'Satılık Köşk', 'İstanbul Satılık...",19 Ocak 2022,Satılık,840 m2,21 Ve Üzeri,4,Boş,Bilinmiyor,İkinci El,NaN,NaN,3,NaN,19 Ocak 2022,Konut,700 m2,8+ Oda,Düz Giriş,Isıtma Yok,Krediye Uygun,Hayır,Ahşap,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## cleaning price column

In [19]:
def clean_price(val):
    try:
        val = val.split('TL')[0].replace(',','')
        return float(val)
    except(ValueError,AttributeError) as e:
        raise ValueError(f"Could not convert price '{val}' to numeric value") from e

In [21]:
df.price = df.price.apply(clean_price)

In [23]:
df.price

0         3100000.0
1         1600000.0
2        18500000.0
3         9500000.0
4        25000000.0
            ...
25150     1850000.0
25151     1100000.0
25152     9000000.0
25153    13000000.0
25154     1000000.0
Name: price, Length: 25155, dtype: float64

## cleaning GrossSquareMeters column

In [26]:
def clean_m2(val):
    try:
        val = val.split(" ")[0]
        return float(val)
    except (ValueError, AttributeError) as e:
        raise ValueError(f"Could not convert area '{area_str}' to numeric value") from e

In [28]:
df.GrossSquareMeters = df.GrossSquareMeters.apply(clean_m2)

In [30]:
df.GrossSquareMeters

0        160.0
1        120.0
2        350.0
3        550.0
4        840.0
         ...
25150    180.0
25151     52.0
25152    176.0
25153    170.0
25154     55.0
Name: GrossSquareMeters, Length: 25155, dtype: float64

## price_per_m2 column

In [33]:
df['price_per_m2'] = df.price / df.GrossSquareMeters

In [35]:
df.price_per_m2

0        19375.000000
1        13333.333333
2        52857.142857
3        17272.727273
4        29761.904762
             ...
25150    10277.777778
25151    21153.846154
25152    51136.363636
25153    76470.588235
25154    18181.818182
Name: price_per_m2, Length: 25155, dtype: float64

In [47]:
df.head()

,district,price,address,AdUpdateDate,Category,GrossSquareMeters,BuildingAge,NumberFloorsofBuilding,UsingStatus,EligibilityForInvestment,BuildStatus,TitleStatus,ItemStatus,NumberOfBathrooms,NumberOfWCs,AdCreationDate,Type,NetSquareMeters,NumberOfRooms,FloorLocation,HeatingType,CreditEligibility,InsideTheSite,StructureType,MortgageStatus,Swap,Balcony,PriceStatus,RentalIncome,NumberOfBalconies,BalconyType,HallSquareMeters,WCSquareMeters,IsItVideoNavigable?,Subscription,BathroomSquareMeters,BalconySquareMeters,price_per_m2
0,adalar,3100000.0,"['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",24 Şubat 2022,Satılık,160.0,21 Ve Üzeri,3,Mülk Sahibi Oturuyor,Bilinmiyor,NaN,NaN,Eşyalı,2,NaN,24 Şubat 2022,Konut,120 m2,3+1,Çatı Katı,Kombi Doğalgaz,Krediye Uygun,Hayır,NaN,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19375.000000
1,adalar,1600000.0,"['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",02 Mart 2022,Satılık,120.0,5-10,3,Mülk Sahibi Oturuyor,Yatırıma Uygun,İkinci El,Kat Mülkiyeti,Eşyalı,1,1,21 Şubat 2022,Konut,100 m2,2+1,Bahçe Katı,Kombi Doğalgaz,Krediye Uygun,Hayır,Betonarme,Yok,Yok,Var,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13333.333333
2,adalar,18500000.0,"['Anasayfa', 'Satılık Müstakil Ev', 'İstanbul ...",11 Şubat 2022,Satılık,350.0,21 Ve Üzeri,2,Mülk Sahibi Oturuyor,Bilinmiyor,NaN,NaN,Boş,3,NaN,11 Şubat 2022,Konut,300 m2,3+1,Düz Giriş,Kombi Doğalgaz,Krediye Uygun,Hayır,NaN,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52857.142857
3,adalar,9500000.0,"['Anasayfa', 'Satılık Bina', 'İstanbul Satılık...",11 Şubat 2022,Satılık,550.0,11-15,3,Mülk Sahibi Oturuyor,Bilinmiyor,İkinci El,NaN,NaN,4,NaN,03 Şubat 2022,Konut,540 m2,8+ Oda,Düz Giriş,Kombi Doğalgaz,Krediye Uygun Değil,Hayır,Betonarme,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17272.727273
4,adalar,25000000.0,"['Anasayfa', 'Satılık Köşk', 'İstanbul Satılık...",19 Ocak 2022,Satılık,840.0,21 Ve Üzeri,4,Boş,Bilinmiyor,İkinci El,NaN,NaN,3,NaN,19 Ocak 2022,Konut,700 m2,8+ Oda,Düz Giriş,Isıtma Yok,Krediye Uygun,Hayır,Ahşap,NaN,Yok,NaN,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29761.904762

## days_on_market column

In [49]:
locale.setlocale(locale.LC_TIME, 'turkish')

'Turkish_Türkiye.1254'

In [69]:
df.AdUpdateDate = pd.to_datetime(df.AdUpdateDate, format='%d %B %Y')
df.AdCreationDate = pd.to_datetime(df.AdCreationDate, format='%d %B %Y')

In [71]:
df['days_on_market'] = df.AdUpdateDate - df.AdCreationDate

In [73]:
df.days_on_market

0          0 days
1          9 days
2          0 days
3          8 days
4          0 days
           ...
25150    341 days
25151    539 days
25152    789 days
25153    975 days
25154   1380 days
Name: days_on_market, Length: 25155, dtype: timedelta64[ns]

## Correlation map